repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: ruff-format
        name: Ruff format
        entry: uv run ruff format
        language: system
        types_or: [python, pyi]
